import { writable } from "svelte/store";
import { browser } from '$app/env';

let today = new Date();
let dd = String(today.getUTCDate());
let mm = String(today.getUTCMonth());
let months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
let mmm = months[mm];
let yyyy = today.getUTCFullYear();
let todaysDate = mmm + dd + yyyy;

let userData = JSON.parse(browser && localStorage.getItem("user")) || {
    firstVisit: true,
    lastDate: todaysDate,
    lastGuessNo: 0,
    lastGuessArtist: '',
    lastGuessAlbum: '',
    guessedArtist: undefined,
    guessedAlbum: undefined,
    gameWon: false,
    gameLost: false,
}
export let user = writable(browser && userData);
user.subscribe(
    (val) => browser && (localStorage.user = JSON.stringify(val))
)

let statsData = JSON.parse(browser && localStorage.getItem("stats")) || {
    totalPoints: 0,
    playCount: 0,
    gamesWon: 0,
    gamesLost: 0,
    winPerc: 0,
    streak: 0,
    maxStreak: 0,
    pointsDist: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}
export let stats = writable(browser && statsData);
stats.subscribe(
    (val) => browser && (localStorage.stats = JSON.stringify(val))
)

let Data = {
    Jul192022: {
        date: todaysDate,
        artist: 'Kendrick Lamar',
        artist2: 'Kendrick Lamar',
        album: 'Damn.',
        album2: 'Damn',
        hint1: 'Genre: Hip Hop',
        hint2: 'Release date: 2017',
        info: 'This album cover was designed by Vlad Sepetov. The red, all caps "DAMN." in Times New Roman font was creating a lot of discussion about "bad" design when it was released. Sepetov himself described the cover as "loud and abrasive". Billboard listed it as one of the best of 2017, dubbing it "both meme-able and memorable".',
        spotify: 'https://open.spotify.com/album/4eLPsYPBmXABThSJ821sqY?si=8_hd2MNtTIWGCMw8RzoZZA',
        applemusic: 'https://music.apple.com/ee/album/damn/1440881047',
    },
    Jul202022: {
        date: todaysDate,
        artist: 'Kendrick Lamar',
        artist2: 'Kendrick Lamar',
        album: 'Damn.',
        album2: 'Damn',
        hint1: 'Genre: Hip Hop',
        hint2: 'Release date: 2017',
        info: 'This album cover was designed by Vlad Sepetov. The red, all caps "DAMN." in Times New Roman font was creating a lot of discussion about "bad" design when it was released. Sepetov himself described the cover as "loud and abrasive". Billboard listed it as one of the best of 2017, dubbing it "both meme-able and memorable".',
        spotify: 'https://open.spotify.com/album/4eLPsYPBmXABThSJ821sqY?si=8_hd2MNtTIWGCMw8RzoZZA',
        applemusic: 'https://music.apple.com/ee/album/damn/1440881047',
    },
    Jul212022: {
        date: todaysDate,
        artist: 'Michael Jackson',
        artist2: 'Michael Jackson',
        album: 'Thriller',
        album2: 'Thriller',
        hint1: 'Genre: Funk / Soul, Pop',
        hint2: 'Release date: 1982',
        info: 'The cover for Thriller features Jackson in a white suit that belonged to photographer Dick Zimmerman. The gatefold sleeve reveals a tiger cub at Jackson\'s leg, which, according to Zimmerman, Jackson kept away from his face, fearing he would be scratched. Another picture from the shoot, with Jackson embracing the cub, was used for the 2001 special edition of Thriller.',
        spotify: 'https://open.spotify.com/album/2ANVost0y2y52ema1E9xAZ?si=F98jSvMLSQqp1hQ4gnZD_g',
        applemusic: 'https://music.apple.com/ee/album/thriller/269572838',
    },
    Jul222022: {
        date: todaysDate,
        artist: 'Nirvana',
        artist2: 'Nirvana',
        album: 'Nevermind',
        album2: 'Nevermind',
        hint1: 'Genre: Rock',
        hint2: 'Release date: 1991',
        info: 'This, one of the most famous album covers in popular music was shot by photographer Kirk Weddle. The fishhook with a dollar bill was added later on Kurt Cobain\'s direction. People at Geffen Records were concerned that the infant\'s penis, visible in the photo, would cause offense, and prepared an alternate cover without it; they relented when Cobain said the only compromise he would accept would be a sticker covering the penis reading: "If you\'re offended by this, you must be a closet pedophile." The cover also features the iconic Nirvana logo, using the Onyx typeface. It was done by former Sub-Pop Art Director Lisa Orth, who\'s mainly working on generative art now.',
        spotify: 'https://open.spotify.com/album/2UJcKiJxNryhL050F5Z1Fk?si=kDkKff8VT_eRvfkL1DXp6w',
        applemusic: 'https://music.apple.com/ee/album/nevermind/1440783617',
    },
    Jul232022: {
        date: todaysDate,
        artist: 'Tame Impala',
        artist2: 'Tame Impala',
        album: 'Currents',
        album2: 'Currents',
        hint1: 'Genre: Rock',
        hint2: 'Release date: 2015',
        info: 'The cover art for Currents and its accompanying singles was created by Kentucky-based artist and musician Robert Beatty. Kevin Parker (Tame Impala) has said Currents\' designs are based on a diagram of vortex shedding he remembered while trying to visualise the album\'s themes. Beatty described how Parker\'s ideas for the album artwork "were all based on turbulent flow, the way liquid or air flows around objects."',
        spotify: 'https://open.spotify.com/album/79dL7FLiJFOO0EoehUHQBv?si=QvQZC3McQOeJVGv_nET2jg',
        applemusic: 'https://music.apple.com/ee/album/currents/1440838039',
    },
    Jul242022: {
        date: todaysDate,
        artist: 'Gorillaz',
        artist2: 'Gorillaz',
        album: 'Demon Days',
        album2: 'Demon Days',
        hint1: 'Genre: Electronic, Hip Hop, Rock, Funk / Soul',
        hint2: 'Release date: 2005',
        info: 'The front cover of "Demon Days" features profiles of Gorillaz\' fictional characters Murdoc, 2D, Noodle and Russel, which were designed by Jamie Hewlett. This rather simple 4x4 layout could easily be a spoof of The Beatles "Let it be" cover.',
        spotify: 'https://open.spotify.com/album/0bUTHlWbkSQysoM3VsWldT?si=EWxJcAPGR3mKPtLVhqSZrg',
        applemusic: 'https://music.apple.com/ee/album/demon-days/850571319',
    },
    Jul252022: {
        date: todaysDate,
        artist: 'Radiohead',
        artist2: 'Radiohead',
        album: 'In Rainbows',
        album2: 'In Rainbows',
        hint1: 'Genre: Electronic, Rock',
        hint2: 'Release date: 2007',
        info: 'Designed by longtime Radiohead collaborator Stanley Donwood. He worked in the studio while Radiohead worked on the album, allowing the artwork to convey the mood of the music. Images were displayed in the studio and on the studio computer for the band to interact with and comment on. "In Rainbows" was the first pay-what-you-want release from a major musical act.',
        spotify: 'https://open.spotify.com/album/5vkqYmiPBYLaalcmjujWxK?si=23pskFDPSVm_omuBelgxzA',
        applemusic: 'https://music.apple.com/ee/album/in-rainbows/1109714933',
    },
    Jul262022: {
        date: todaysDate,
        artist: 'Daft Punk',
        artist2: 'Daft Punk',
        album: 'Random Access Memories',
        album2: 'Random Access Memories',
        hint1: 'Genre: Electronic, Funk / Soul, Pop',
        hint2: 'Release date: 2013',
        info: 'Unlike the previous studio albums that feature the band\'s wordmark as the cover art, Random Access Memories is the first and only one to not do so. Instead, it features the band members\' signature helmets with the album title written on the top left. The font is reminiscent to that of Michael Jackson\'s Thriller.',
        spotify: 'https://open.spotify.com/album/4m2880jivSbbyEGAKfITCa?si=_LCcmFpKRMakzLCktR1EtQ',
        applemusic: 'https://music.apple.com/ee/album/random-access-memories/617154241',
    },
    Jul272022: {
        date: todaysDate,
        artist: 'The Fugees',
        artist2: 'Fugees',
        album: 'The Score',
        album2: 'Score',
        hint1: 'Genre: Hip Hop',
        hint2: 'Release date: 1996',
        info: 'One of the best selling albums of all time. Cover photo by Marc Baptiste.',
        spotify: 'https://open.spotify.com/album/4z6F5s3RVaOsekuaegbLfD?si=lV4K4iDmTaC8yY21JQuYzA',
        applemusic: 'https://music.apple.com/ee/album/the-score/281701670',
    },
    Jul282022: {
        date: todaysDate,
        artist: 'The Beatles',
        artist2: 'Beatles',
        album: 'Abbey Road',
        album2: 'Abbey Road',
        hint1: 'Genre: Rock',
        hint2: 'Release date: 1969',
        info: 'This infamous cover photo was taken from the stepladder in the middle of the Abbey Road by Iain Macmillan in a 15-minute photoshoot. The license plate on the white Volkswagen Beetle (LMW 281F) in the back was repeatedly stolen after the album was released.',
        spotify: 'https://open.spotify.com/album/0ETFjACtuP2ADo6LFhL6HN?si=pLWu1lAsRx6r8u23lPcQmQ',
        applemusic: 'https://music.apple.com/ee/album/abbey-road-remastered/1441164426',
    },
    Jul292022: {
        date: todaysDate,
        artist: 'Talking Heads',
        artist2: 'Talkingheads',
        album: 'Remain in light',
        album2: 'Remain in light',
        hint1: 'Genre: Electronic, Rock',
        hint2: 'Release date: 1980',
        info: 'Initial name for the album was planned as "Melody attack", but the cover design process made them realize it did not fit with the music. It was one of the first computer-designed record jackets. The process was tortuous because computer power was limited in the early 1980s and the mainframe alone took up several rooms.',
        spotify: 'https://open.spotify.com/album/3AQgdwMNCiN7awXch5fAaG?si=sJX0wluhT7ucBdCOT8yqeQ',
        applemusic: 'https://music.apple.com/ee/album/remain-in-light-deluxe-version/124922154',
    },
    Jul302022: {
        date: todaysDate,
        artist: 'The Prodigy',
        artist2: 'Prodigy',
        album: 'The fat of the land',
        album2: 'Fat of the land',
        hint1: 'Genre: Electronic',
        hint2: 'Release date: 1997',
        info: 'Although the cover itself is a bit confusing, it\'s the first time the famous ant logo made it\'s appearance. The album title comes from the old English phrase "living off the fat of the land", which means living well or being wealthy.',
        spotify: 'https://open.spotify.com/album/4fdgcEVMdJe0KVgupMNJAP?si=sUY4RQnBQHeaZdUbAbkQZQ',
        applemusic: 'https://music.apple.com/ee/album/the-fat-of-the-land/1450123945',
    },
    Jul312022: {
        date: todaysDate,
        artist: 'Grace Jones',
        artist2: 'Grace Jones',
        album: 'Island Life',
        album2: 'Island Life',
        hint1: 'Genre: Reggae, Funk / Soul, Pop',
        hint2: 'Release date: 1985',
        info: 'This compilation album cover was created by photographer, illustrator and graphic designer Jean-Paul Goude, who was Jones\' partner at the time. This impossibly graceful pose is actually a montage of separate images, following Goude\'s ideas on creating credible illusions with his cut-and-paint technique.',
        spotify: 'https://open.spotify.com/album/0IgaRsWGL9c4bovxkwU7YI?si=sON_y1cZQV-le2A-9543Kg',
        applemusic: 'https://music.apple.com/ee/album/island-life/1564504203',
    },
    Aug12022: {
        date: todaysDate,
        artist: 'Lady Gaga',
        artist2: 'Lady Gaga',
        album: 'The Fame Monster',
        album2: 'Fame Monster',
        hint1: 'Genre: Electronic, Rock, Pop',
        hint2: 'Release date: 2009',
        info: 'A reissue of Lady Gaga\'s debut studio album, The Fame. Two covers were created for The Fame Monster, both of which were shot by French photographer and fashion designer Hedi Slimane.',
        spotify: 'https://open.spotify.com/album/6rePArBMb5nLWEaY9aQqL4?si=rrj00f8LQ6CAIIprsbWfog',
        applemusic: 'https://music.apple.com/ee/album/the-fame-monster-deluxe-edition/1476727669',
    },
    Aug22022: {
        date: todaysDate,
        artist: 'Metallica',
        artist2: 'Metallica',
        album: 'Master of puppets',
        album2: 'Master of puppets',
        hint1: 'Genre: Rock',
        hint2: 'Release date: 1986',
        info: 'The cover art was made by illustrator and painter Don Brautigam in just three days, using a combination of airbrush and paintbrush. He had never heard a note of music from the album, not even "Disposable Heroes," which is frequently cited as the reference for the soldier\'s helmet on the cross headstone to the far left. Obviously, the concept for the artwork came from Metallica and their manager.',
        spotify: 'https://open.spotify.com/album/2Lq2qX3hYhiuPckC8Flj21?si=eWMRNq_HR9qCRTX3Hk9neA',
        applemusic: 'https://music.apple.com/ee/album/master-of-puppets-remastered/1440901428',
    },
    Aug32022: {
        date: todaysDate,
        artist: 'The Weeknd',
        artist2: 'Weeknd',
        album: 'After Hours',
        album2: 'After Hours',
        hint1: 'Genre: Electronic, Hip Hop, Funk / Soul, Pop',
        hint2: 'Release date: 2020',
        info: 'The title of the album was inspired by the 1985 movie of the same name by Martin Scorsese. The album\'s overall art direction was primarily handled by the Tammi brothers, with its design being handled by Aleksi Tammi, and its photography and visual direction being handled by Anton Tammi, who directed the music videos for the album\'s singles, and the project\'s same-titled short film.',
        spotify: 'https://open.spotify.com/album/4yP0hdKOZPNshxUOjY0cZj?si=9xIT3Bs7QfGa4js4mlj1fw',
        applemusic: 'https://music.apple.com/ee/album/after-hours/1499378108',
    },
    Aug42022: {
        date: todaysDate,
        artist: 'Fleetwood Mac',
        artist2: 'Fleetwood Mac',
        album: 'Rumours',
        album2: 'Rumours',
        hint1: 'Genre: Rock',
        hint2: 'Release date: 1977',
        info: 'The cover art features singer Stevie Nicks and drummer Mick Fleetwood. The black and white photo was shot by Herbert Worthington. And yes, Mick is wearing two wooden balls between his legs.',
        spotify: 'https://open.spotify.com/album/1bt6q2SruMsBtcerNVtpZB?si=HmXE1cIBQae5TMISk0-6jQ',
        applemusic: 'https://music.apple.com/ee/album/rumours/594061854',
    },
    Aug52022: {
        date: todaysDate,
        artist: 'Bruce Springsteen',
        artist2: 'Bruce Springsteen',
        album: 'Born in the USA',
        album2: 'Born in the U.S.A.',
        hint1: 'Genre: Rock',
        hint2: 'Release date: 1984',
        info: 'Springsteen\'s butt, blue jeans and american flag. Shot by legendary photographer Annie Leibovitz.',
        spotify: 'https://open.spotify.com/album/0PMasrHdpaoIRuHuhHp72O?si=-PPHAdLERXKS9q22fE7E-Q',
        applemusic: 'https://music.apple.com/ee/album/born-in-the-u-s-a/203708420',
    },
}
let todaysData = Data[todaysDate];
export default todaysData;