import { writable } from "svelte/store";
import { browser } from '$app/env';

let today = new Date();
let dd = String(today.getUTCDate());
let mm = String(today.getUTCMonth());
let months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
let mmm = months[mm];
let yyyy = today.getUTCFullYear();
let todaysDate = mmm + dd + yyyy;

let userData = JSON.parse(browser && localStorage.getItem("user")) || {
    firstVisit: true,
    lastDate: todaysDate,
    lastGuessNo: 0,
    lastGuessArtist: '',
    lastGuessAlbum: '',
    guessedArtist: undefined,
    guessedAlbum: undefined,
    gameWon: false,
    gameLost: false,
}
export let user = writable(browser && userData);
user.subscribe(
    (val) => browser && (localStorage.user = JSON.stringify(val))
)

let statsData = JSON.parse(browser && localStorage.getItem("stats")) || {
    totalPoints: 0,
    playCount: 0,
    gamesWon: 0,
    gamesLost: 0,
    winPerc: 0,
    streak: 0,
    maxStreak: 0,
    pointsDist: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}
export let stats = writable(browser && statsData);
stats.subscribe(
    (val) => browser && (localStorage.stats = JSON.stringify(val))
)

let Data = {
    Nov182022: {
        date: todaysDate,
        artist: 'Sade',
        artist2: 'Sade',
        album: 'The Best Of Sade',
        album2: 'The Best Of',
        hint1: 'Genre: Soul, Smooth Jazz',
        hint2: 'Country: UK',
        hint3: 'Release date: 1994',
        info: 'First best-of album in our quiz. The cover is shot by Scottish fashion, celebrity and art photographer Albert Watson. He has created major advertising campaigns for clients such as Prada, Chanel and Levis. Watson has also taken some well-known photographs, from the portrait of Steve Jobs that appeared on the cover of his biography, a photo of Alfred Hitchcock holding a plucked goose, and a portrait of a nude Kate Moss taken on her 19th birthday.',
        spotify: 'https://open.spotify.com/album/3uSWaQxJAdm5MWKQkQJNoK?si=p_TNEFigRYSg2NMUzNThzw',
        applemusic: 'https://music.apple.com/ee/album/the-best-of-sade/604770232',
    },
    Nov192022: {
        date: todaysDate,
        artist: 'Vampire Weekend',
        artist2: 'Vampire Weekend',
        album: 'Vampire Weekend',
        album2: 'Vampire Weekend',
        hint1: 'Genre: Indie Pop',
        hint2: 'Country: USA',
        hint3: 'Release date: 2008',
        info: 'The album’s cover depicts the chandelier in St. Anthony Hall, a Columbia University semi-secret society. The photo is a Polaroid picture from one of the band’s early shows at Columbia.',
        spotify: 'https://open.spotify.com/album/5fedTyx7AnXeyxLL0giq6x?si=0pFvYJ65TiezEG71rsYnGw',
        applemusic: 'https://music.apple.com/ee/album/vampire-weekend/271489741',
    },
    Nov202022: {
        date: todaysDate,
        artist: 'New Order',
        artist2: 'New Order',
        album: 'Power, Corruption & Lies',
        album2: 'Power Corruption and Lies',
        hint1: 'Genre: Synth-Pop, New Wave, Post-Punk',
        hint2: 'Country: UK',
        hint3: 'Release date: 1983',
        info: 'Another cover from Peter Saville. It’s a reproduction of the painting "A Basket of Roses" by French artist Henri Fantin-Latour, which is part of the National Gallery’s permanent collection in London. Saville had originally planned to use a Renaissance portrait of a dark prince to tie in with the Machiavellian theme of the title, but could not find a suitable portrait. At the gallery Saville picked up a postcard with Fantin-Latour’s painting, and his girlfriend mockingly asked him if he was going to use it for the cover. Fashion designer Raf Simons and street-fashion label Supreme have both used the cover in their collections.',
        spotify: 'https://open.spotify.com/album/6NTrwu1XJ56jBPx7HMksbZ?si=rk3hKEBcT8Sbzup_-fwFpQ',
        applemusic: 'https://music.apple.com/ee/album/power-corruption-lies/1040981945',
    },
    Nov212022: {
        date: todaysDate,
        artist: 'A Tribe Called Quest',
        artist2: 'Tribe Called Quest',
        album: 'The Low End Theory',
        album2: 'Low End Theory',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 1991',
        info: '“Following up the sunny day illustration from their happy-go-lucky debut, Tribe went decidedly darker on the cover for the more mature (and classic) The Low End Theory. Painting the contours of an invisible model’s body with glow-in-the-dark paint, the red, green, and black image was sexy and Afrocentric all at once—a delicate balance that mirrored Tribe’s jazz-heavy sound at the time. The iconic imagery would continue to pop up throughout Tribe’s career (gracing the covers of their next two albums), making the painted lady hip-hop’s most recognizable mascot. Stripped-down, stylish, and original, The Low End Theory is everything a great rap album cover should be.” via Conplex. AD: ZombArt, Photography: Joe Gran1',
        spotify: 'https://open.spotify.com/album/1p12OAWwudgMqfMzjMvl2a?si=QEj6ZLq6SXiStj36ilUPUw',
        applemusic: 'https://music.apple.com/ee/album/the-low-end-theory/278911460',
    },
    Nov222022: {
        date: todaysDate,
        artist: 'Aphex Twin',
        artist2: 'Aphex Twin',
        album: 'Drukqs',
        album2: 'Drugs',
        hint1: 'Genre: Electronic, IDM, Classical',
        hint2: 'Country: England (Irish-born)',
        hint3: 'Release date: 2001',
        info: 'Supposedly a photo from inside his Yamaha Disklavier, which was connected to a computer to control it, to give some tracks that “human, but not-quite” feel.',
        spotify: 'https://open.spotify.com/album/1maoQPAmw44bbkNOxKlwsx?si=W0JU2tIWRtSOitgBtcH-_A',
        applemusic: 'https://music.apple.com/ee/album/drukqs/282559693',
    },
    Nov232022: {
        date: todaysDate,
        artist: 'Pet Shop Boys',
        artist2: 'Pet Shop Boys',
        album: 'Actually',
        album2: 'Actually',
        hint1: 'Genre: Synth-Pop',
        hint2: 'Country: England',
        hint3: 'Release date: 1987',
        info: 'Designed by Pet Shop Boys’ long time collaborator Mark Farrow (@farrowlondon). Cover photo by Cindy Palmano. Although not released as a single, the track "Shopping" is frequently featured as background music in British television news and current affairs programmes dealing with retail business issues and as bumper music on home shopping shows. This is despite the fact that the song is actually a critique of privatisation in 1980s Britain, and has little to do with actual shopping.',
        spotify: 'https://open.spotify.com/album/0p5QwhEke5P9mFY4CY9u4j?si=WwsS1dlVTmOt_8P9HrH8fw',
        applemusic: 'https://music.apple.com/ee/album/actually-2018-remaster/1645128416',
    },
    Nov242022: {
        date: todaysDate,
        artist: 'Public Enemy',
        artist2: 'Public Enemy',
        album: 'It Takes a Nation of Millions to Hold Us Back',
        album2: 'It Takes a Nation',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 1988',
        info: '#15, and highest Hip Hop album in the Rolling Stones’ “500 greatest albums of all time” list. Cover photo by American photographer Glen E. Friedman who has worked with punk and hip hop artists like Black Flag, Dead Kennedys, Beastie Boys, Run-DMC, to name a few.',
        spotify: 'https://open.spotify.com/album/03Mx6yaV7k4bsEmcTH8J49?si=471Ah5X-QeObDgJJPoGyaA',
        applemusic: 'https://music.apple.com/ee/album/it-takes-a-nation-of-millions-to-hold-us-back/1440837788',
    },
    Nov252022: {
        date: todaysDate,
        artist: 'Radiohead',
        artist2: 'Radiohead',
        album: 'Kid A',
        album2: 'Kid A',
        hint1: 'Genre: Electronic, Alternative Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 2000',
        info: 'The Kid A artwork and packaging was created by Thom Yorke with Stanley Donwood, who has worked with Radiohead since their 1994 EP My Iron Lung. Donwood painted on large canvases with knives and sticks, then photographed the paintings and manipulated them with Photoshop. While working on the artwork, Yorke and Donwood became "obsessed" with the Worldwatch Institute website, which was full of "scary statistics about ice caps melting, and weather patterns changing"; this inspired them to use an image of a mountain range as the cover art.',
        spotify: 'https://open.spotify.com/album/6GjwtEZcfenmOf6l18N7T7?si=IVtGhgEDRtuJJK-izC-ksg',
        applemusic: 'https://music.apple.com/ee/album/kid-a/1097862870',
    },
    Nov262022: {
        date: todaysDate,
        artist: 'Solange',
        artist2: 'Solange',
        album: 'A Seat At The Table',
        album2: 'Seat At The Table',
        hint1: 'Genre: Neo Soul',
        hint2: 'Country: US',
        hint3: 'Release date: 2016',
        info: 'From the interview with her sister Beyoncé, Solange said about the cover: "I wanted to create an image that invited people to have an up-close and personal experience—and that really spoke to the album title—that communicated, through my eyes and my posture, like, “Come and get close. It’s not going to be pretty. It’s not going to be perfect. It’s going to get a little gritty, and it might get a little intense, but it’s a conversation we need to have.” I wanted to nod to the Mona Lisa and the stateliness, the sternness that that image has.”',
        spotify: 'https://open.spotify.com/album/3Yko2SxDk4hc6fncIBQlcM?si=A9i2LbiPRIGnfa7KXN5OHQ',
        applemusic: 'https://music.apple.com/ee/album/a-seat-at-the-table/1159507212',
    },
    Nov272022: {
        date: todaysDate,
        artist: 'Mike Oldfield',
        artist2: 'Mike Oldfield',
        album: 'Tubular Bells',
        album2: 'Tubular Bells',
        hint1: 'Genre: Progressive Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 1973',
        info: 'The cover of Tubular Bells was created by designer and photographer Trevor Key. The backdrop was photographed in Sussex, England and the triangular "bent bell" on the front was inspired by the damage Oldfield had caused to the tubular bells while playing them on the record. Key was paid £100 for his work, but he went on to design several other sleeves for Virgin and Factory Records artists.',
        spotify: 'https://open.spotify.com/album/0a3YQpBnRzJzNktOjb6Dum?si=xN5__0FAQ-C7juF2X0iU5Q',
        applemusic: 'https://music.apple.com/ee/album/tubular-bells/1440852773',
    },
    Nov282022: {
        date: todaysDate,
        artist: 'Nine Inch Nails',
        artist2: 'NIN',
        album: 'The Downward Spiral',
        album2: 'The Downward Spiral',
        hint1: 'Genre: Industrial Rock, ALternative Rock',
        hint2: 'Country: US (Ohio)',
        hint3: 'Release date: 1994',
        info: 'When Trent Reznor contacted British collagist Russell Mills in 1994 about creating a cover for The Downward Spiral, he had a list of words he wanted the art to evoke. Chief among them were "attrition," "wound," and "decay”. The result you see here is made of plaster, acrylics, oils, rusted metals, insects, moths, Mills’ blood, wax, varnishes, and surgical bandaging on a wooden panel.',
        spotify: 'https://open.spotify.com/album/5I7lLu8xXJfGRdFUqHaLQU?si=AgNlsFZKS4acFlTXmh671Q',
        applemusic: 'https://music.apple.com/ee/album/the-downward-spiral-deluxe-edition/1418210351',
    },
    Nov292022: {
        date: todaysDate,
        artist: 'Outkast',
        artist2: 'Outcast',
        album: 'Aquemini',
        album2: 'Aquemini',
        hint1: 'Genre: Hip Hop, Southern Hip Hop',
        hint2: 'Country: US (Atlanta, Georgia)',
        hint3: 'Release date: 1998',
        info: 'Illustrated by Greg Hawkins, designed and art directed by LaFace Records in-house designer D.L. Warfield. The former has worked on many covers for the record label — for TLC, Toni Braxton, Usher etc.',
        spotify: 'https://open.spotify.com/album/5ceB3rxgXqIRpsOvVzTG28?si=bqhrtqZLT9GYfIqi5ZsyCw',
        applemusic: 'https://music.apple.com/ee/album/aquemini/266365274',
    },
    Nov302022: {
        date: todaysDate,
        artist: 'Taylor Swift',
        artist2: 'Taylor Swift',
        album: 'Midnights',
        album2: 'Midnights (3am Edition)',
        hint1: 'Genre: Pop',
        hint2: 'Country: US',
        hint3: 'Release date: 2022',
        info: 'The standard cover artwork takes inspiration from old-fashioned LP jackets whose songs were listed on the front cover. The typeface used here is Neue Haas Grotesk. Three limited-edition color variants of the physical album, featuring different cover artworks were also issued. Photographed by Beth Garrabrant (@bethgarrabrant)',
        spotify: 'https://open.spotify.com/album/151w1FgRZfnKZA9FEcg9Z3?si=423W60w5T7mIcDUORUCV-w',
        applemusic: 'https://music.apple.com/ee/album/midnights/1649434004',
    },
    Dec12022: {
        date: todaysDate,
        artist: 'Beastie Boys',
        artist2: 'Beastie Boys',
        album: 'Check Your Head',
        album2: 'Check Your Head',
        hint1: 'Genre: Hip Hop, Rap Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1992',
        info: 'The album was somewhat of a return by the Beastie Boys to their punk roots. It featured the trio playing their own instruments on the majority of the album, for the first time on record since their early EPs, due to the commercial failure of Paul’s Boutique. This inspired photographer Glen E. Friedman to shoot photos of the Beasties with their instrument cases, one of which was used as the cover of the album.',
        spotify: 'https://open.spotify.com/album/7CSP7J60QKIBCqOV64qILq?si=JHAmELEHTxCGx-cRrhVuLw',
        applemusic: 'https://music.apple.com/ee/album/check-your-head-deluxe-version-remastered/724303425',
    },
    Dec22022: {
        date: todaysDate,
        artist: 'The Jimi Hendrix Experience',
        artist2: 'Jimi Hendrix',
        album: 'Axis: Bold As Love',
        album2: 'Axis',
        hint1: 'Genre: Psychedelic Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1967',
        info: 'The album cover depicts Hendrix and the Experience as various forms of Vishnu, incorporating a painting of the musicians by Roger Law, from a photo-portrait by Karl Ferris. Hendrix expressed dismay at the choice of cover art. He stated that the cover would have been more appropriate had it highlighted his Native American heritage. Also, some Hindus have since expressed anger over the use of religious images for the album’s artwork.',
        spotify: 'https://open.spotify.com/album/3uFZf8rykoHo7XMIQVYW6r?si=KzVVrZK8RIGAEF4po6qK-g',
        applemusic: 'https://music.apple.com/ee/album/axis-bold-as-love/344562307',
    },
    Dec32022: {
        date: todaysDate,
        artist: 'Spice Girls',
        artist2: 'Spice Girls',
        album: 'Spice',
        album2: 'Spice',
        hint1: 'Genre: Pop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1996',
        info: '“Spice” is considered to be the record that brought teen pop back, opening the doors for a wave of teen pop artists. Conceptually, the album centered on the idea of Girl Power, and the hype surrounding the group was compared to Beatlemania (it was dubbed "Spicemania").',
        spotify: 'https://open.spotify.com/album/3x2jF7blR6bFHtk4MccsyJ?si=UuumCxZVSeO1h5oewyHXXQ',
        applemusic: 'https://music.apple.com/ee/album/spice/723398173',
    },
    Dec42022: {
        date: todaysDate,
        artist: 'George Michael',
        artist2: 'George Michael',
        album: 'Faith',
        album2: 'Faith',
        hint1: 'Genre: Pop, Funk/Soul, Synth-Pop, Pop Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 1987',
        info: 'Cover photo by Russell Young. The symbols below the album name stand for: Faith, Music, Money, Religion, Love.',
        spotify: 'https://open.spotify.com/album/34K1Kvskt9arWy8E1Gz3Lw?si=Iaq2FzFDTdyh-ij9UhEXBQ',
        applemusic: 'https://music.apple.com/ee/album/faith-2010-remaster/395918916',
    },
    Dec52022: {
        date: todaysDate,
        artist: 'Dr. Dre',
        artist2: 'Dr Dre',
        album: 'The Chronic',
        album2: 'Chronic',
        hint1: 'Genre: Hip Hop, Gangsta Rap',
        hint2: 'Country: US (Los Angeles, California)',
        hint3: 'Release date: 1992',
        info: 'Designed by Kimberly Holt, the cover is an homage to Zig-Zag rolling papers.',
        spotify: '',
        applemusic: '',
    },
    Dec62022: {
        date: todaysDate,
        artist: 'Daft Punk',
        artist2: 'Daft Punk',
        album: 'Homework',
        album2: 'Homework',
        hint1: 'Genre: House, Techno, Disco',
        hint2: 'Country: France',
        hint3: 'Release date: 1997',
        info: 'The artwork for the front cover and inner sleeve was conceived by Daft Punk, photographed by artist and film producer Nicolas Hidiroglou. Homem-Christo had previously designed the Daft Punk wordmark, which was the basis for this image.',
        spotify: 'https://open.spotify.com/album/5uRdvUR7xCnHmUW8n64n9y?si=a8CejEX7SK2njoV9s7GsTw',
        applemusic: 'https://music.apple.com/ee/album/homework/696884422',
    },
    Dec72022: {
        date: todaysDate,
        artist: 'Black Sabbath',
        artist2: 'Black Sabbath',
        album: 'Master Of Reality',
        album2: 'Masters Of Reality',
        hint1: 'Genre: Heavy Metal, Doom Metal',
        hint2: 'Country: England',
        hint3: 'Release date: 1971',
        info: 'The first editions of Master of Reality came in an “envelope sleeve” containing a poster of the band, and with the album’s title embossed in black lettering, visible in relief. On the first North American editions of the album incorrectly listed the album title as Masters of Reality. Art Director: Mike Stanford',
        spotify: 'https://open.spotify.com/album/3kBG6q0aXKxzn01wKTwZr5?si=4kNylw7kQ82KvrfD2Zk_MA',
        applemusic: 'https://music.apple.com/ee/album/master-of-reality-2009-remastered-version/1193822439',
    },
    Dec82022: {
        date: todaysDate,
        artist: 'Madonna',
        artist2: 'Madonna',
        album: 'Madonna',
        album2: 'Madonna',
        hint1: 'Genre: Pop, Synth-Pop',
        hint2: 'Country: US',
        hint3: 'Release date: 1983',
        info: 'The album cover was shot by photographer Gary Heery and directed by Carin Goldberg. The album was re-released in 1985 for the European market and re-packaged as Madonna: The First Album with a different artwork created by photographer George Holy. The cover features Madonna in similar style of dress to the original cover but this time with crucifix as her earrings.',
        spotify: 'https://open.spotify.com/album/1DWWb4Q39mp1T3NgyscowF?si=yBOGU3YERuWrTrEKTWolVA',
        applemusic: 'https://music.apple.com/ee/album/madonna-bonus-tracks-2001-remaster/80815644',
    },
    Dec92022: {
        date: todaysDate,
        artist: 'David Bowie',
        artist2: 'David Bowie',
        album: 'David Bowie',
        album2: 'Space Oddity',
        hint1: 'Genre: Rock, Psychedelic Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 1969',
        info: 'The original UK cover artwork features a photograph by British photographer Vernon Dewhurst, exposed on top of a work by Victor Vasarely — a Hungarian-French artist, who is widely accepted as a "grandfather" and leader of the Op art movement. The artwork, was designed by Bowie and Lee, who enthusiastically collected Vasarely’s works.',
        spotify: 'https://open.spotify.com/album/1ay9Z4R5ZYI2TY7WiDhNYQ?si=8C2YeIprQnOu5We72Ch9LA',
        applemusic: 'https://music.apple.com/ee/album/david-bowie-2015-remaster/1039799506',
    },
    Dec112022: {
        date: todaysDate,
        artist: 'Coldplay',
        artist2: 'Coldplay',
        album: 'Viva la Vida or Death and All His Friends',
        album2: 'Viva la Vida',
        hint1: 'Genre: Rock, Pop Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 2008',
        info: 'Viva la Vida takes its artwork from Eugène Delacroix’s 1830 painting Liberty Leading the People.',
        spotify: 'https://open.spotify.com/album/1CEODgTmTwLyabvwd7HBty?si=9wxa4lYsTf-tpLOK_C8PQA',
        applemusic: 'https://music.apple.com/ee/album/viva-la-vida-or-death-and-all-his-friends/1122773394',
    },
    Dec122022: {
        date: todaysDate,
        artist: 'The Chemical Brothers',
        artist2: 'Chemical Brothers',
        album: 'Push the Button',
        album2: 'Push the Button',
        hint1: 'Genre: Electronic/Dance, Big Beat',
        hint2: 'Country: UK',
        hint3: 'Release date: 2005',
        info: 'Inspired by the protest posters of the past, this cover was illustrated by Kam Tang. Art Directed by a graphic design duo Tappin Gofton (Mark Tappin and Simon Gofton), who did the previous Coldplay “Viva la Vida” album as well.',
        spotify: 'https://open.spotify.com/album/715rku55lldqdw9WiEuPgi?si=3X8ytvhSSXyIamTq5wuVZQ',
        applemusic: 'https://music.apple.com/ee/album/push-the-button/724514728',
    },
    Dec132022: {
        date: todaysDate,
        artist: '2Pac',
        artist2: '2 Pac',
        album: 'All Eyez on Me',
        album2: 'All Eyes on Me',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 1996',
        info: 'All Eyez on Me was the second album by 2Pac to chart at number one on both the Billboard 200 and the Top R&B/Hip-Hop Albums charts, selling 566,000 copies in the first week. Seven months later, 2Pac was fatally wounded in a drive-by shooting. Cover photograph shot by Ken Nahoum.',
        spotify: 'https://open.spotify.com/album/78iX7tMceN0FsnmabAtlOC?si=7qTtIqJ-SwitPqEzdHtA2w',
        applemusic: 'https://music.apple.com/ee/album/all-eyez-on-me/1588480719',
    },
    Dec142022: {
        date: todaysDate,
        artist: 'Portishead',
        artist2: 'Portishead',
        album: 'Dummy',
        album2: 'Dummy',
        hint1: 'Genre: Trip Hop, Downtempo',
        hint2: 'Country: UK',
        hint3: 'Release date: 1994',
        info: 'The cover of the album is a still image of vocalist Beth Gibbons taken from To Kill a Dead Man—the short film that the band created—for which the self-composed soundtrack earned the band its record contract.',
        spotify: 'https://open.spotify.com/album/3539EbNgIdEDGBKkUf4wno?si=wA2LFM0mSPOZEWRaLCyzpA',
        applemusic: 'https://music.apple.com/ee/album/dummy/1440653096',
    },
    Dec152022: {
        date: todaysDate,
        artist: 'Bad Bunny',
        artist2: 'Bad Bunny',
        album: 'Un Verano Sin Ti',
        album2: 'Un Verano Sin Ti',
        hint1: 'Genre: Reggaeton, Pop Rap, Pop',
        hint2: 'Country: Puerto Rico',
        hint3: 'Release date: 2022',
        info: 'If you follow Spotify’s streaming lists, you’ve probably seen this album cover week in and out. Boasting with a whopping 9,914,668,592 streams as of today, this all-Spanish language LP is one of the most streamed albums out there.',
        spotify: 'https://open.spotify.com/album/3RQQmkQEvNCY4prGKE6oc5?si=0ltOhEQQRQ2TZJhn6txgfQ',
        applemusic: 'https://music.apple.com/ee/album/un-verano-sin-ti/1622045624',
    },
    Dec162022: {
        date: todaysDate,
        artist: 'The Killers',
        artist2: 'The Killers',
        album: 'Hot Fuss',
        album2: 'Hot Fuss',
        hint1: 'Genre: Rock, New Wave',
        hint2: 'Country: US',
        hint3: 'Release date: 2004',
        info: 'The album cover was photographed by Matthias Clamer in 2000, in the southern region of the suburbs of Beijing, China. The characters on top of each building ("建", "材", "开", and "发") translate to "construction material development".',
        spotify: 'https://open.spotify.com/album/4piJq7R3gjUOxnYs6lDCTg?si=XZwF3xnORPqUSClS7LQlGQ',
        applemusic: 'https://music.apple.com/ee/album/hot-fuss-deluxe-edition/1440717563',
    },
    Dec172022: {
        date: todaysDate,
        artist: 'Bob Marley & the Wailers',
        artist2: 'Bob Marley',
        album: 'Legend',
        album2: 'The Best Of',
        hint1: 'Genre: Reggae',
        hint2: 'Country: Jamaica',
        hint3: 'Release date: 1984',
        info: 'As of 13 December 2022, Legend has spent a total of 760 nonconsecutive weeks on the Billboard 200 albums chart—the second longest run in history. Cover photo by one of Britain’s best-known music photographers Adrian Boot.',
        spotify: 'https://open.spotify.com/album/4jKeipwuUTjlx9USNYdhZn?si=MS89FCwoTJG6cfJFeDM4QA',
        applemusic: 'https://music.apple.com/ee/album/legend-the-best-of-bob-marley-and-the-wailers-remastered/1469575763',
    },
    Dec182022: {
        date: todaysDate,
        artist: 'Pink Floyd',
        artist2: 'Pink Floyd',
        album: 'Wish You Were Here',
        album2: 'Wish You Were Here',
        hint1: 'Genre: Prog Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 1975',
        info: 'The album’s cover images were photographed by Aubrey "Po" Powell, Thorgerson’s partner at the design studio Hipgnosis, and inspired by the idea that people tend to conceal their true feelings, for fear of "getting burned", and thus two businessmen were pictured shaking hands, one man on fire. "Getting burned" was also a common phrase in the music industry, used often by artists denied royalty payments. The photograph was taken at Warner Bros. Studios in California.',
        spotify: 'https://open.spotify.com/album/6uvBKDGlJAYLH5Vy6RQVsc?si=HemceW8GS9SWxHNc-ysdVw',
        applemusic: 'https://music.apple.com/ee/album/wish-you-were-here/704223460',
    },
    Dec192022: {
        date: todaysDate,
        artist: 'Erykah Badu',
        artist2: 'Eryka Badu',
        album: 'Baduizm',
        album2: 'Baduism',
        hint1: 'Genre: Neo Soul',
        hint2: 'Country: US',
        hint3: 'Release date: 1997',
        info: 'Along with fellow contemporary albums such as D’Angelo’s Brown Sugar and Maxwell’s Urban Hang Suite, Baduizm’s success helped establish Badu as one of the leading artists in the neo-soul genre and is one of the albums credited with contributing to the genre’s commercial visibility at the time. Cover photo by Marc Baptiste.',
        spotify: 'https://open.spotify.com/album/3qr4pTBWEU1SVf01j6RAx3?si=nbAudY9SQe28sd2GOooWig',
        applemusic: 'https://music.apple.com/ee/album/baduizm/1440837269',
    },
    Dec202022: {
        date: todaysDate,
        artist: 'John Coltrane',
        artist2: 'John Coltrain',
        album: 'Blue Train',
        album2: 'Blue Train',
        hint1: 'Genre: Jazz, Hard Bop, Saxophone Jazz',
        hint2: 'Country: US',
        hint3: 'Release date: 1958',
        info: 'Recorded at the Van Gelder Studio in Hackensack, New Jersey, it is the only Blue Note recording by Coltrane as session leader. It has been certified a gold record by the RIAA.',
        spotify: 'https://open.spotify.com/album/2Z11cXWEa2qqYQBGkJrCga?si=CaenRyzVSqqMVN17gRbVNg',
        applemusic: 'https://music.apple.com/ee/album/blue-train/1468202477',
    },
    Dec212022: {
        date: todaysDate,
        artist: 'The Doors',
        artist2: 'The Doors',
        album: 'The Doors',
        album2: 'The Doors',
        hint1: 'Genre: Psychedelic Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1967',
        info: 'The Doors remains the band’s best-selling studio album, with sales of over 13 million copies, as of 2015. For the album’s cover, Joel Brodsky was hired to provide a photo of the group, which later received a Grammy nomination.',
        spotify: 'https://open.spotify.com/album/1jWmEhn3ggaL6isoyLfwBn?si=XzgZs7jeQae0j9zec8dKWw',
        applemusic: 'https://music.apple.com/ee/album/the-doors/1622368510',
    },
    Dec222022: {
        date: todaysDate,
        artist: 'Eminem',
        artist2: 'Eminem',
        album: 'The Marshall Mathers LP',
        album2: 'The Marshall Mathers',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 2000',
        info: 'The Marshall Mathers LP was released with three different album covers. The original features Eminem sitting on the porch of the house he lived in during his teenage years. The other cover features the rapper seated in a fetal position beneath a loading dock with alcohol and prescription pill bottles at his feet. Third one is a portrait of him behind a table.',
        spotify: 'https://open.spotify.com/album/5H0rjI1TW8F2tORPYMJXHJ?si=BPxyI3I-QNqlsz0PFuybxw',
        applemusic: 'https://music.apple.com/ee/album/the-marshall-mathers-lp/1453737727',
    },
    Dec232022: {
        date: todaysDate,
        artist: 'Queen',
        artist2: 'Queen',
        album: 'A Night at the Opera',
        album2: 'Night at the Opera',
        hint1: 'Genre: Rock, Pop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1975',
        info: 'The cover artwork features the band’s logo, which was designed by Mercury himself, on a white background. The band’s next album, A Day at the Races, featured a similar design but on a black background.',
        spotify: 'https://open.spotify.com/album/1GbtB4zTqAsyfZEsm1RZfx?si=lpa9yYFATr6Tkr7Wt5-DKw',
        applemusic: 'https://music.apple.com/ee/album/a-night-at-the-opera/1440854433',
    },
    Dec242022: {
        date: todaysDate,
        artist: 'Elvis Presley',
        artist2: 'Elvis',
        album: "Elvis' Christmas Album",
        album2: 'Elvis Christmas Album',
        hint1: 'Genre: Pop, Gospel, Ballad',
        hint2: 'Country: US',
        hint3: 'Release date: 1957',
        info: 'Even rarer than the cover and record itself is a gold foil price tag-shaped "gift giving" sticker attached to the shrink wrap, reading "TO ___, FROM ___, ELVIS SINGS". Original copies with the gold sticker intact on the shrink wrap have proven to be among the most valuable of Presley’s albums. Adding to its already high value are limited red vinyl albums and album covers with gold print down the spine. With total sales of more 20 million copies worldwide, it remains the world’s best-selling Christmas album and one of the best-selling albums of all time.',
        spotify: 'https://open.spotify.com/album/6zk4RKl6JFlgLCV4Z7DQ7N?si=j5XgT7snRpq5q8oC3l7SpA',
        applemusic: 'https://music.apple.com/ee/album/elvis-christmas-album/676288305',
    },
    Dec252022: {
        date: todaysDate,
        artist: 'Mariah Carey',
        artist2: 'Mariah Carey',
        album: 'Merry Christmas',
        album2: 'Merry Christmas',
        hint1: 'Genre: Pop, Ballad',
        hint2: 'Country: US',
        hint3: 'Release date: 1994',
        info: 'As of 2021, Merry Christmas has sold 15 million copies worldwide, becoming one of the best-selling holiday albums of all time.',
        spotify: 'https://open.spotify.com/album/61ulfFSmmxMhc2wCdmdMkN?si=-ZHTlZZzRO-JNlrla57XzQ',
        applemusic: 'https://music.apple.com/ee/album/merry-christmas/585972750',
    },
    Dec262022: {
        date: todaysDate,
        artist: 'Neneh Cherry',
        artist2: 'Neneh Cherry',
        album: 'Raw Like Sushi',
        album2: 'Raw Like Sushi',
        hint1: 'Genre: Hip Hop, New Jack Swing, R&B',
        hint2: 'Country: UK / born in Sweden',
        hint3: 'Release date: 1989',
        info: 'The cover and inner photos for “Raw Like Sushi” were shot by fashion photographer Jean-Baptiste Mondino.',
        spotify: 'https://open.spotify.com/album/2AyJzvREOnlnYhaBzF1Kxp?si=2LAghRi_QkKL8n3ZyF2I4A',
        applemusic: 'https://music.apple.com/ee/album/raw-like-sushi/716751901',
    },
    Dec272022: {
        date: todaysDate,
        artist: 'Arctic Monkeys',
        artist2: 'Arctic Monkeys',
        album: 'Favourite Worst Nightmare',
        album2: 'Favorite Worst Nightmare',
        hint1: 'Genre: Rock, Indie Rock, Garage Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 2007',
        info: 'The cover features a photograph of a dark, bland house in Liverpool, with illuminated rooms, where local artists painted the inside walls with colourful pieces. The band said they also considered naming the album Lesbian Wednesdays, Gordon Brown, or Gary Barlow.',
        spotify: 'https://open.spotify.com/album/1XkGORuUX2QGOEIL4EbJKm?si=pDHzaK23SwaNKQhEABGidg',
        applemusic: 'https://music.apple.com/ee/album/favourite-worst-nightmare/251126923',
    },
    Dec282022: {
        date: todaysDate,
        artist: 'Mac Miller',
        artist2: 'Mc Miller',
        album: 'Swimming',
        album2: 'Swimming',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 2018',
        info: 'Full of meaning, the overall cover has often been posed as a combination of Miller’s previous works. The central vertical stripe references the debut Blue Slide Park, the central facial expression from WMWTSO, a white background from GO:OD AM, and a suit the tone of Divine Feminine. Photographed by Christian Weber.',
        spotify: 'https://open.spotify.com/album/5wtE5aLX5r7jOosmPhJhhk?si=yOR3v2EAQ8yTunb5TRl9tA',
        applemusic: 'https://music.apple.com/ee/album/swimming/1408996052',
    },
    Dec292022: {
        date: todaysDate,
        artist: 'Bon Jovi',
        artist2: 'Bon Jovi',
        album: 'Slippery When Wet',
        album2: 'Slippery When Wet',
        hint1: 'Genre: Rock, Pop Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1986',
        info: 'The album originally was to feature a busty woman in a wet yellow T-shirt with the album name on the front of the shirt. Sambora said, "Our label freaked out a bit when they saw what we’d done. They thought it would be banned by American stores, so we had to come up with something else – fast." In Japan, most releases of the album still included the original cover art.',
        spotify: 'https://open.spotify.com/album/0kBfgEilUFCMIQY5IOjG4t?si=bf0ibKQYR1aEcKBt27U50Q',
        applemusic: 'https://music.apple.com/ee/album/slippery-when-wet/1422954626',
    },
    Dec302022: {
        date: todaysDate,
        artist: 'The Beatles',
        artist2: 'Beatles',
        album: 'Let It Be',
        album2: 'Let It Be',
        hint1: 'Genre: Rock, Pop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1970',
        info: 'The LP cover was designed by John Kosh and photographed by Ethan Russell. The album title appears in white text above the images but, as on Abbey Road and other Beatles LPs, the cover does not include the band’s name.',
        spotify: 'https://open.spotify.com/album/0jTGHV5xqHPvEcwL8f6YU5?si=u30KebtbSom4OmR48c82wA',
        applemusic: 'https://music.apple.com/ee/album/let-it-be/1441164495',
    },
    Dec312022: {
        date: todaysDate,
        artist: 'ABBA',
        artist2: 'ABBA',
        album: 'Super Trouper',
        album2: 'Super Trooper',
        hint1: 'Genre: Pop',
        hint2: 'Country: Sweden',
        hint3: 'Release date: 1980',
        info: 'Super Trouper is a registered trademark owned by Strong Entertainment Lighting, for their brand of followspots, i.e., directional spotlights used to follow a performer on stage. Album cover designer, Rune Söderqvist, decided to use the spotlight theme and photograph the group, surrounded by circus performers, at Piccadilly Circus, London.',
        spotify: 'https://open.spotify.com/album/3ZdkT5buYFi1WQaB0XNNtf?si=tFW9CDzsQDKy5qqbskOV4g',
        applemusic: 'https://music.apple.com/ee/album/super-trouper-bonus-track-version/1440823811',
    },
    Jan12023: {
        date: todaysDate,
        artist: 'Rick Astley',
        artist2: 'Rick Astley',
        album: 'Whenever You Need Somebody',
        album2: 'Whenever You Need Somebody',
        hint1: 'Genre: Pop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1987',
        info: 'VICE has a great documentary on Youtube about him called “The Legendary Song That Became the Rick Roll”. Well worth the watch. On the tracklist, there’s a writing credit of Dick Spatsley on "The Love Has Gone" which was a reference to a running gag by Smash Hits magazine that deliberately misspelled his name.',
        spotify: 'https://open.spotify.com/album/5Z9iiGl2FcIfa3BMiv6OIw?si=p6qqwVzgRSW1MBKJTyrGPA',
        applemusic: 'https://music.apple.com/ee/album/whenever-you-need-somebody-2022-remaster/1626265761',
    },
    Jan22023: {
        date: todaysDate,
        artist: 'Green Day',
        artist2: 'Green Day',
        album: 'Dookie',
        album2: 'Dookie',
        hint1: 'Genre: Pop Punk',
        hint2: 'Country: US',
        hint3: 'Release date: 1994',
        info: 'The album artwork by fellow East Bay punk Richie Bucher caused controversy, since it depicted bombs being dropped on people and buildings. The setting is a replica of Berkeley’s Telegraph Avenue in California. The robed character that looks like the Mona Lisa is the woman on the cover of the first Black Sabbath album. AC/DC guitarist Angus Young is in there somewhere too. The graffiti reading "Twisted Dog Sisters" refers to two girls from Berkeley. The guy saying "The fritter, fat boy" was a reference to a local cop.',
        spotify: 'https://open.spotify.com/album/4uG8q3GPuWHQlRbswMIRS6?si=8xJpXBt9SYWeNVePNJ-_cA',
        applemusic: 'https://music.apple.com/ee/album/dookie/1160081985',
    },
    Jan32023: {
        date: todaysDate,
        artist: 'Kanye West',
        artist2: 'Kanye West',
        album: 'Yeezus',
        album2: 'Jesus',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 2013',
        info: 'The packaging consists of little more than a piece of red tape and a sticker affixed to the back, with sample credits and the album’s barcode. West himself explained the album cover: "The whole concept for the Yeezus album is that we’re not going to be using CDs in the future and since this is the last time we’re going to see it, this is an open casket for the CD."',
        spotify: 'https://open.spotify.com/album/7D2NdGvBHIavgLhmcwhluK?si=P_yMDNJ-S9Kx_h78zRKiag',
        applemusic: 'https://music.apple.com/ee/album/yeezus/1440873068',
    },
    Jan42023: {
        date: todaysDate,
        artist: 'Whitney Houston',
        artist2: 'Whitney Houston',
        album: 'Whitney',
        album2: 'Whitney',
        hint1: 'Genre: Pop, Dance, R&B',
        hint2: 'Country: US',
        hint3: 'Release date: 1987',
        info: 'Photographed by an American fashion and portrait photographer Richard Avedon. He has photographed many celebrities, including The Beatles, Marilyn Monroe, Andy Warhol and Electric Light Orchestra to name a few.',
        spotify: 'https://open.spotify.com/album/5Vdzprr5cOqXQo44eHeV7t?si=cZNJhMYBQ7yWC0ebdZ01lQ',
        applemusic: 'https://music.apple.com/ee/album/whitney/840431884',
    },
    Jan52023: {
        date: todaysDate,
        artist: 'Meat Loaf',
        artist2: 'Meat Loaf',
        album: 'Bat Out of Hell',
        album2: 'Bat Out of Hell',
        hint1: 'Genre: Hard Rock, Pop Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1977',
        info: 'Composer Jim Steinman is credited with the concept for the album cover. The illustration was done by Richard Corben, an American illustrator and comic book artist known for his comics in Heavy Metal magazine.',
        spotify: 'https://open.spotify.com/album/6mvI80w5r78niBmwtu7RF9?si=PChVPNKsSJ-LKgG0r82pwg',
        applemusic: 'https://music.apple.com/ee/album/bat-out-of-hell/991385383',
    },
    Jan62023: {
        date: todaysDate,
        artist: 'Adele',
        artist2: 'Adele',
        album: '30',
        album2: '30',
        hint1: 'Genre: Pop, Soul',
        hint2: 'Country: UK',
        hint3: 'Release date: 2021',
        info: 'Best selling album of 2021. A handful of deluxe physical editions of the album were made available for purchase through selected retailers, including cassette tapes on Adele’s webstore. Cover photo shot by British celebrity and beauty photographer Simon Emmett.',
        spotify: 'https://open.spotify.com/album/21jF5jlMtzo94wbxmJ18aa?si=1ROK90oYRgqnoIgdev6G1w',
        applemusic: 'https://music.apple.com/ee/album/30/1590035691',
    },
    Jan72023: {
        date: todaysDate,
        artist: 'Massive Attack',
        artist2: 'Massive Attack',
        album: 'Blue Lines',
        album2: 'Blue Lines',
        hint1: 'Genre: Trip Hop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1991',
        info: 'The font used on the cover of the album is Helvetica Black Oblique. Del Naja has acknowledged the influence of the inflammable material logo used on the cover of Stiff Little Fingers’ album Inflammable Material.',
        spotify: 'https://open.spotify.com/album/5mAPk4qeNqVLtNydaWbWlf?si=b3aAWOZLQWiJg5t-SJYtpg',
        applemusic: 'https://music.apple.com/ee/album/blue-lines-2012-mix-master/715864097',
    },
    Jan82023: {
        date: todaysDate,
        artist: 'Sade',
        artist2: 'Sade',
        album: 'Diamond Life',
        album2: 'Diamond Life',
        hint1: 'Genre: Soul, Smooth Jazz',
        hint2: 'Country: UK',
        hint3: 'Release date: 1984',
        info: 'Diamond Life sold over 10 million copies worldwide, becoming one of the top-selling debut recordings of the era and the best-selling debut album by a British female vocalist, a record that stood for 24 years.',
        spotify: 'https://open.spotify.com/album/3JcNnjMVSKiNpqhErZarW0?si=1A3_B6WlRpGE7I9fZCvpNw',
        applemusic: 'https://music.apple.com/ee/album/diamond-life/1524651063',
    },
    Jan92023: {
        date: todaysDate,
        artist: 'SZA',
        artist2: 'SZA',
        album: 'SOS',
        album2: 'SOS',
        hint1: 'Country: US, Genre: R&B',
        hint2: 'Release date: 2022',
        hint3: 'Both artist name and album name are 3-letter acronyms',
        info: 'The cover of SOS depicts SZA, a former marine biology major, perched on a diving board. She was inspired by a 1997 photograph of Princess Diana on Mohamed Al Fayed’s yacht taken one week before her death and said she wanted to pay homage to the “isolation” it conveyed.',
        spotify: 'https://open.spotify.com/album/07w0rG5TETcyihsEIZR3qG?si=LQecaIcyT6eqZUODO_9jiw',
        applemusic: 'https://music.apple.com/ee/album/sos/1657869377',
    },
    Jan102023: {
        date: todaysDate,
        artist: 'Phil Collins',
        artist2: 'Phil Collins',
        album: 'Face Value',
        album2: 'Face Value',
        hint1: 'Genre: Rock, Pop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1981',
        info: 'Collins regarded Face Value as a highly personal project, which gave rise to the iconic cover art with Collins’ face in extreme close-up, originally intended to symbolise the listener "getting into his head"; the reverse side of the sleeve shows the rear of his head. To emphasise the personal nature of the album, Collins also hand wrote all of the liner and sleeve notes, even down to the legal statements on the outer circumference of the centre label of the disc itself. For the 2016 reissues, Collins re-shot all his original album cover portraits, where he looks quite a bit older.',
        spotify: 'https://open.spotify.com/album/7gUgpwRHL95RLPi2WmqxgU?si=ek2wC179QvyfiP2oDDA8aQ',
        applemusic: 'https://music.apple.com/ee/album/face-value-remastered/1076060805',
    },
    Jan112023: {
        date: todaysDate,
        artist: 'Beyoncé',
        artist2: 'Beyonce',
        album: 'Lemonade',
        album2: 'Lemonade',
        hint1: 'Genre: R&B',
        hint2: 'Country: US',
        hint3: 'Release date: 2016',
        info: 'In a similar fashion to her eponymous 2013 album, Lemonade’s artwork shifts the attention from Beyoncé’s face and image to the music and visuals she’s created. The cover photo for Lemonade is from the music "Don’t Hurt Yourself”.',
        spotify: 'https://open.spotify.com/album/7dK54iZuOxXFarGhXwEXfF?si=JK8fGFgwQQC0flSgLEjI3w',
        applemusic: 'https://music.apple.com/ee/album/lemonade/1460430561',
    },
    Jan122023: {
        date: todaysDate,
        artist: 'Guns N\' Roses',
        artist2: 'Guns and Roses',
        album: 'Appetite for Destruction',
        album2: 'Appetite for Destruction',
        hint1: 'Genre: Hard Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1987',
        info: 'The album’s original cover art was based on Robert Williams’ painting Appetite for Destruction. It depicted a robotic rapist about to be punished by a metal avenger. After several music retailers refused to stock the album, the label compromised and put the controversial cover art inside, replacing it with an image depicting a Celtic cross and skulls of the five band members with (designed by Billy White Jr., originally as a tattoo), each skull representing one member of the band.',
        spotify: 'https://open.spotify.com/album/3I9Z1nDCL4E0cP62flcbI5?si=gBv6zYvMTRCC_9iuuseuIw',
        applemusic: 'https://music.apple.com/ee/album/appetite-for-destruction/1377813284',
    },
    Jan132023: {
        date: todaysDate,
        artist: 'Lizzo',
        artist2: 'Lizzo',
        album: 'Special',
        album2: 'Special',
        hint1: 'Genre: Pop, Funk, Disco, Hip Hop, R&B',
        hint2: 'She\'s an American singer, rapper, and flutist',
        hint3: 'Release date: 2022',
        info: 'Lizzo said in an April interview with Sirius XM’s The Heat that she wrote "175 to 200 songs," but only 12 made the album. Cover photo shot by AB+DM Studio.',
        spotify: 'https://open.spotify.com/album/1NgFBv1PxMG1zhFDW1OrRr?si=1617Ka2-R6W7cW_PucpYlA',
        applemusic: 'https://music.apple.com/ee/album/special/1634655863',
    },
    Jan142023: {
        date: todaysDate,
        artist: 'AC/DC',
        artist2: 'AC/DC',
        album: 'Back in Black',
        album2: 'Back in Black',
        hint1: 'Genre: Hard Rock, Heavy Metal',
        hint2: 'Country: Australia',
        hint3: 'Release date: 1980',
        info: '“Back in black” is the band’s first album to feature lead singer Brian Johnson, following the death of previous lead singer Bon Scott. The album’s all-black cover was designed as a "sign of mourning" for Scott.',
        spotify: 'https://open.spotify.com/album/6mUdeDZCsExyJLMdAfDuwh?si=S9_EVH4hRUeyKMZi63IMZg',
        applemusic: 'https://music.apple.com/ee/album/back-in-black/574050396',
    },
    Jan152023: {
        date: todaysDate,
        artist: 'Oasis',
        artist2: 'Oasis',
        album: '(What\'s the Story) Morning Glory?',
        album2: 'Morning Glory',
        hint1: 'Genre: Rock, Britpop',
        hint2: 'Country: UK',
        hint3: 'Release date: 1995',
        info: 'The cover is a picture of two men passing each other on Berwick Street in London. The two men are London DJ Sean Rowley and album sleeve designer Brian Cannon (back to the camera). The album’s producer Owen Morris can be seen in the background, on the left footpath, holding the album’s master tape in front of his face. The location was chosen because the street was a popular location for record shops at the time.',
        spotify: 'https://open.spotify.com/album/2u30gztZTylY4RG7IvfXs8?si=9nutBVGOSQy1N3-uzE5N3A',
        applemusic: 'https://music.apple.com/ee/album/whats-the-story-morning-glory/1517447039',
    },
    Jan162023: {
        date: todaysDate,
        artist: 'The Beatles',
        artist2: 'Beatles',
        album: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        album2: 'Sgt. Pepper',
        hint1: 'Genre: Rock, Pop, Psychedelia',
        hint2: 'Country: UK',
        hint3: 'Release date: 1967',
        info: 'The cover was art-directed by Robert Fraser and photographed by Michael Cooper. Blake recalled of the concept: "I offered the idea that if they had just played a concert in the park, the cover could be a photograph of the group just after the concert with the crowd who had just watched the concert, watching them.” Fearing controversy, EMI rejected Lennon’s request for images of Adolf Hitler and Jesus Christ and Harrison’s for Mahatma Gandhi. Each of the Beatles sports a heavy moustache, after Harrison had first grown one as a disguise during his visit to India. ',
        spotify: 'https://open.spotify.com/album/6QaVfG1pHYl1z15ZxkvVDW?si=yoxEQp64QO2WiiJmafm3gQ',
        applemusic: 'https://music.apple.com/ee/album/sgt-peppers-lonely-hearts-club-band/1441164604',
    },
    Jan172023: {
        date: todaysDate,
        artist: 'TLC',
        artist2: 'TLC',
        album: 'CrazySexyCool',
        album2: 'Crazy Sexy Cool',
        hint1: 'Genre: R&B',
        hint2: 'Country: US',
        hint3: 'Release date: 1994',
        info: 'Lead single, "Creep", topped the Billboard Hot 100 for four weeks. "Waterfalls", became TLC’s most successful song, spending seven weeks at number one. It was also the second-biggest single of 1995 according to Billboard, earning TLC two songs in the top three of the 1995 Billboard year-end chart.',
        spotify: 'https://open.spotify.com/album/5eg56dCpFn32neJak2vk0f?si=99SD3b0jRk2r7E9qVGvxtg',
        applemusic: 'https://music.apple.com/ee/album/crazysexycool/270246704',
    },
    Jan182023: {
        date: todaysDate,
        artist: 'Rolling Stones',
        artist2: 'Rolling Stones',
        album: 'Let It Bleed',
        album2: 'Let It Bleed',
        hint1: 'Genre: Rock, Blues',
        hint2: 'Country: US',
        hint3: 'Release date: 1969',
        info: 'The album cover displays a surreal sculpture designed by Robert Brownjohn. The artwork was inspired by the working title of the album, which was Automatic Changer. Jagger originally asked artist M. C. Escher to design a cover for the album, but he declined.',
        spotify: 'https://open.spotify.com/album/4l4u9e9jSbotSXNjYfOugy?si=VI-bxymfS-eFptgPfTZoOw',
        applemusic: 'https://music.apple.com/ee/album/let-it-bleed-remastered/1500642838',
    },
    Jan192023: {
        date: todaysDate,
        artist: 'Outkast',
        artist2: 'Outcast',
        album: 'Aquemini',
        album2: 'Aquemini',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US (Atlanta)',
        hint3: 'Release date: 1998',
        info: 'Illustrated by Greg Hawkins and art directed by DL Warfield. The title of the album is a portmanteau of the zodiac signs of Big Boi and André 3000—Aquarius and Gemini.',
        spotify: 'https://open.spotify.com/album/5ceB3rxgXqIRpsOvVzTG28?si=_VtelZjDQFqKFSE0OzbJ8A',
        applemusic: 'https://music.apple.com/ee/album/aquemini/266365274',
    },
    Jan202023: {
        date: todaysDate,
        artist: 'Janet Jackson',
        artist2: 'Janet Jackson',
        album: 'Control',
        album2: 'Control',
        hint1: 'Genre: Pop, R&B',
        hint2: 'Country: US',
        hint3: 'Release date: 1986',
        info: 'The cover for “Control” was shot and stylized by fashion photographer Tony Viramontes. Also the single covers for songs “Nasty” and “Control”.',
        spotify: 'https://open.spotify.com/album/7GWkceE5McMVfffd1RGL6Y?si=o9aT3FMiQoO22oJq4PYnWA',
        applemusic: 'https://music.apple.com/ee/album/control/1440831636',
    },
    Jan212023: {
        date: todaysDate,
        artist: 'Led Zeppelin',
        artist2: 'Led Zeppelin',
        album: 'IV',
        album2: '4',
        hint1: 'Genre: Hard Rock, Heavy Metal',
        hint2: 'Country: UK',
        hint3: 'Release date: 1971',
        info: 'The 19th-century rustic oil painting on the front of the album was purchased from an antique shop in Reading, Berkshire by Plant. The painting was then juxtaposed and affixed to the internal, papered wall of a partly demolished suburban house for the photograph to be taken. In place of a title, Page decided each member could choose a personal emblem for the cover. Initially thinking of a single symbol, he then decided there could be four, with each member of the band choosing his own.',
        spotify: 'https://open.spotify.com/album/5EyIDBAqhnlkAHqvPRwdbX?si=1MgU-fidQG65aC3g8IPScw',
        applemusic: 'https://music.apple.com/ee/album/led-zeppelin-iv-remastered/580708175',
    },
    Jan222023: {
        date: todaysDate,
        artist: 'Rihanna',
        artist2: 'Rihanna',
        album: 'Unapologetic',
        album2: 'Unapologetic',
        hint1: 'Genre: Pop, Synth-Pop, R&B',
        hint2: 'Country: US',
        hint3: 'Release date: 2012',
        info: 'Mario Hugo was commissioned to provide art direction, illustration, treatments, custom typography and album art design for Rihanna’s Unapologetic. The creative was developed through experimental processes including transfers and chemical treatment. The packaging features photography by Michael Muller and Melissa Forde.',
        spotify: 'https://open.spotify.com/album/5pLlGJrxuQO3jMoQe1XxZY?si=AY9BJnEFSaCd-fbs7kJ4Xg',
        applemusic: 'https://music.apple.com/ee/album/unapologetic-deluxe-version/1417177082',
    },
    Jan232023: {
        date: todaysDate,
        artist: 'David Bowie',
        artist2: 'Ziggy Stardust',
        album: 'Aladdin Sane',
        album2: 'Aladin Sane',
        hint1: 'Genre: Rock, Glam Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 1973',
        info: 'The cover artwork, shot by Brian Duffy and featuring a lightning bolt across Bowie’s face, was the most expensive cover ever made at the time and represents the split personality of the Aladdin Sane character and Bowie’s mixed feelings of the tour and stardom.',
        spotify: 'https://open.spotify.com/album/3HZKOk1knxrUU3y5ZIOdbz?si=6Wnoddy0RoOb6MtGqmIKrQ',
        applemusic: 'https://music.apple.com/ee/album/aladdin-sane-2013-remaster/1039655668',
    },
    Jan242023: {
        date: todaysDate,
        artist: 'Patti Smith',
        artist2: 'Patti Smith',
        album: 'Horses',
        album2: 'Horses',
        hint1: 'Genre: Punk Rock, Art Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1975',
        info: 'The cover photograph for Horses was taken by Robert Mapplethorpe at the Greenwich Village penthouse apartment of his partner Sam Wagstaff. Smith recalled that Mapplethorpe "took, like, twelve pictures, and at about the eighth one, he said, \'I have it.\' I said, \'How do you know?\' and he said, \'I just know,\' and I said, \'Okay.\' And that was it."',
        spotify: 'https://open.spotify.com/album/0OeuSeP8wp8n8OuTqYb61C?si=oLMO79dgRlGxUvQoto6BUA',
        applemusic: 'https://music.apple.com/ee/album/horses/1038568061',
    },
    Jan252023: {
        date: todaysDate,
        artist: 'D\'Angelo',
        artist2: 'DAngelo',
        album: 'Voodoo',
        album2: 'Vodoo',
        hint1: 'Genre: Neo Soul',
        hint2: 'Country: US',
        hint3: 'Release date: 2000',
        info: 'D’Angelo promoted Voodoo with an international supporting tour in late 2000. While successful early on, the tour became plagued by concert cancellations and D’Angelo’s personal frustrations surrounding his sexualized public image from the album’s marketing. Voodoo has since been regarded by music writers as a creative milestone of the neo soul genre during its apex and has sold more than 1.7 million copies in the United States.',
        spotify: 'https://open.spotify.com/album/2lO9yuuIDgBpSJzxTh3ai8?si=VFL2Deb3Rjebr98pLj2bjQ',
        applemusic: 'https://music.apple.com/ee/album/voodoo/1440841365',
    },
    Jan262023: {
        date: todaysDate,
        artist: 'Kendrick Lamar',
        artist2: 'Kendrick Lamar',
        album: 'To Pimp a Butterfly',
        album2: 'Pimp a Butterfly',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US (Compton, California)',
        hint3: 'Release date: 2015',
        info: 'The cover photo was shot by French photographer Denis Rouvre under the direction of Kendrick Lamar and Dave Free (otherwise known as visual duo The Little Homies). The album was originally going to be titled Tu Pimp a Caterpillar, a backronym for Tu.P.A.C. — a nod to the rapper Tupac.',
        spotify: 'https://open.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP?si=gUxbe08xS6G3q7k3r5Bcgg',
        applemusic: 'https://music.apple.com/ee/album/to-pimp-a-butterfly/1440828886',
    },
    Jan272023: {
        date: todaysDate,
        artist: 'Bob Dylan',
        artist2: 'Bob Dylan',
        album: 'Blood on the Tracks',
        album2: 'Blood on Tracks',
        hint1: 'Genre: Folk Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1975',
        info: 'Paul Till took the cover photo of Dylan at a concert and used different darkroom techniques and hand-colouring, to achieve this look. On a whim, he decided to send Dylan his photos. “I looked up his address in Who’s Who at the library,” Till said. “I thought maybe I’ll get a letter from him saying thanks or something.” Instead, he received a letter from Dylan’s art director, Ron Coro. “They said, your picture has been selected for use on the album cover”.',
        spotify: 'https://open.spotify.com/album/4WD4pslu83FF6oMa1e19mF?si=F1fVaYZPTKK6Qey7dcuBzQ',
        applemusic: 'https://music.apple.com/ee/album/blood-on-the-tracks/158320766',
    },
    Jan282023: {
        date: todaysDate,
        artist: 'The xx',
        artist2: 'The xx',
        album: 'xx',
        album2: 'The xx',
        hint1: 'Genre: Indie Pop, Dream Pop, Indie Rock',
        hint2: 'Country: UK',
        hint3: 'Release date: 2009',
        info: 'Art directed by both the band itself, and Phil Lee, who has been featured here many times already — FKA Twigs and all those Adele covers. The band members met while studying at Elliott School, the same school attended by Hot Chip, Burial, Four Tet, actor Pierce Brosnan, Fleetwood Mac founder Peter Green and singer Matt Monro.',
        spotify: 'https://open.spotify.com/album/2av2ZSHlvD7rvLSsMvtYCG?si=QnG_mHlpRIeDyvqX9Hbj-w',
        applemusic: 'https://music.apple.com/ee/album/xx/325808192',
    },
    Jan292023: {
        date: todaysDate,
        artist: 'The Beatles',
        artist2: 'The Beatles',
        album: 'The Beatles',
        album2: 'White Album',
        hint1: 'Genre: Rock, Pop, Folk',
        hint2: 'Country: UK',
        hint3: 'Release date: 1968',
        info: 'Pop artist Richard Hamilton designed the record sleeve in collaboration with McCartney. The band’s name, in Helvetica, was crookedly blind embossed slightly below the middle of the album’s right side. Later vinyl record releases in the US showed the title in grey printed (rather than embossed) letters.',
        spotify: 'https://open.spotify.com/album/1klALx0u4AavZNEvC4LrTL?si=foYw46WHRa-ry47misIPrg',
        applemusic: 'https://music.apple.com/ee/album/the-beatles-the-white-album/1441133180',
    },
    Jan302023: {
        date: todaysDate,
        artist: 'Billie Eilish',
        artist2: 'Billy Eilish',
        album: 'When We All Fall Asleep, Where Do We Go?',
        album2: 'When We All Fall Asleep, Where Do We Go?',
        hint1: 'Genre: Pop, Electropop',
        hint2: 'Country: US',
        hint3: 'Release date: 2019',
        info: 'Photographed by Kenneth Cappello, with whom Eilish had previously collaborated for the artwork of her 2017 EP Don’t Smile at Me. The singer had prepared sketches for the album cover which were inspired by the album’s themes of night terrors and lucid dreaming, as well as Eilish’s interest in horror films, specifically The Babadook.',
        spotify: 'https://open.spotify.com/album/0S0KGZnfBGSIssfF54WSJh?si=RC2PcgSVTcez80SFcdnMFg',
        applemusic: 'https://music.apple.com/ee/album/when-we-all-fall-asleep-where-do-we-go/1450695723',
    },
    Jan312023: {
        date: todaysDate,
        artist: 'Alanis Morissette',
        artist2: 'Alanis Morisette',
        album: 'Jagged Little Pill',
        album2: 'Jagged Little Pill',
        hint1: 'Genre: Alternative Rock, Post-Grunge, Pop Rock',
        hint2: 'Country: Canada',
        hint3: 'Release date: 1995',
        info: 'Jagged Little Pill was a worldwide commercial success, topping the charts in thirteen countries. With sales of over 33 million copies worldwide, it is one of the best-selling albums of all time and made Morissette the first Canadian to achieve double diamond sales.',
        spotify: 'https://open.spotify.com/album/09AwlP99cHfKVNKv4FC8VW?si=dTyAmcP6RKCZklun3anQDA',
        applemusic: 'https://music.apple.com/ee/album/jagged-little-pill-remastered/1050392837',
    },
    Feb12023: {
        date: todaysDate,
        artist: 'Metallica',
        artist2: 'Metallica',
        album: 'Metallica',
        album2: 'The Black Album',
        hint1: 'Genre: Heavy Metal',
        hint2: 'Country: US',
        hint3: 'Release date: 1991',
        info: 'For the initial release of the album, both emblems were embossed so they could barely be seen against the black background, giving Metallica the nickname "The Black Album". For later and current releases, both emblems are dark gray so they stand out more prominently.',
        spotify: 'https://open.spotify.com/album/2Kh43m04B1UkVcpcRa1Zug?si=Eomqhb96RKK9wY0htMJTfQ',
        applemusic: 'https://music.apple.com/ee/album/metallica-remastered/1571968136',
    },
    Feb22023: {
        date: todaysDate,
        artist: 'Fleet Foxes',
        artist2: 'Fleet Foxes',
        album: 'Fleet Foxes',
        album2: 'Fleet Foxes',
        hint1: 'Genre: Indie Folk, Folk Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 2008',
        info: 'The cover art is a detail of the 1559 painting Netherlandish Proverbs by Pieter Bruegel the Elder. Vocalist/guitarist Robin Pecknold has said: “I liked that the first impression is that it’s just pretty, but then you realize that the scene is this weird chaos. I like that you can’t really take it for what it is, that your first impression of it is wrong.” and “It was very easy to get the museum in Berlin that has it to say yes. They were super excited a band wanted to use it and put it in their newsletter.”',
        spotify: 'https://open.spotify.com/album/1rfgmU0AYNwWfS88pCOlX7?si=iylCtmOLSfCZDHR63PaXNg',
        applemusic: 'https://music.apple.com/ee/album/fleet-foxes/1211881401',
    },
    Feb32023: {
        date: todaysDate,
        artist: 'Norah Jones',
        artist2: 'Norah Jones',
        album: 'Come Away with Me',
        album2: 'Come Away with Me',
        hint1: 'Genre: Acoustic Pop, Jazz, Folk',
        hint2: 'Country: US',
        hint3: 'Release date: 2002',
        info: '“Come Away with Me” has sold over 28 million copies worldwide, making it one of the best-selling albums of all time. Jones is the daughter of Indian sitarist and composer Ravi Shankar.',
        spotify: 'https://open.spotify.com/album/3ul9GmXlTkmRMh3OciXxFR?si=cBDTHSCjR-ibf5HruRvgDA',
        applemusic: 'https://music.apple.com/ee/album/come-away-with-me-remastered/1624173298',
    },
    Feb42023: {
        date: todaysDate,
        artist: 'Thundercat',
        artist2: 'Thunder cat',
        album: 'Drunk',
        album2: 'Drunk',
        hint1: 'Genre: Acid Jazz, Fusion, Funk, Contemporary R&B',
        hint2: 'Country: US',
        hint3: 'Release date: 2017',
        info: 'Designed by Zack Fox and photographed by filmmaker and game designer Eddie Alcaraz. In 2015, Alcazar started his collaboration with American music producer Flying Lotus. The two partnered founding Brainfeeder Films, an independent film finance and production company, mainly focused on supporting experimental projects and emerging artists.',
        spotify: 'https://open.spotify.com/album/7vHBQDqwzB7uDvoE5bncMM?si=24GEAgaqQnOfi5tlc2LC_g',
        applemusic: 'https://music.apple.com/ee/album/drunk/1197789099',
    },
    Feb52023: {
        date: todaysDate,
        artist: 'Madonna',
        artist2: 'Madonna',
        album: 'True Blue',
        album2: 'True Blue',
        hint1: 'Genre: Dance-Pop, Synth-Pop',
        hint2: 'Country: US',
        hint3: 'Release date: 1986',
        info: 'The album cover, shot by photographer Herb Ritts, is one of Madonna’s most recognizable pictures. Andy Warhol’s concept of pop art was one of the inspirations behind the album artwork.',
        spotify: 'https://open.spotify.com/album/6fmnT17jc2Sc69q3nza1eD?si=CS6_qGZlQnuNfyD90Zz7jQ',
        applemusic: 'https://music.apple.com/ee/album/true-blue/80815611?i=80815275',
    },
    Feb62023: {
        date: todaysDate,
        artist: 'Paul Simon',
        artist2: 'Paul Simon',
        album: 'Graceland',
        album2: 'Grace land',
        hint1: 'Genre: Folk Rock, Pop Rock, African',
        hint2: 'Country: US',
        hint3: 'Release date: 1986',
        info: 'The cover art depicts an Ethiopian Christian icon from the collection of the Peabody Essex Museum dating to around 1500.',
        spotify: 'https://open.spotify.com/album/4WoQ94qzwQj28n3nlSOVLB?si=EdWnFUhFRsy2yB4fp7QR5A',
        applemusic: 'https://music.apple.com/ee/album/graceland/529574560',
    },
    Feb72023: {
        date: todaysDate,
        artist: 'LCD Soundsystem',
        artist2: 'LCD Sound System',
        album: 'This Is Happening',
        album2: 'This Is Happening',
        hint1: 'Genre: Dance, Electronic, Disco, Post-Punk',
        hint2: 'Country: US',
        hint3: 'Release date: 2010',
        info: 'Art directed by their long-time collaborator, Michael Vadino. Cover photo by Ruvan Wijesooriya. The first single, "Drunk Girls", was released in April 2010, with a music video directed by Spike Jonze.',
        spotify: 'https://open.spotify.com/album/4hnqM0JK4CM1phwfq1Ldyz?si=LjibtvI6Rg6-ggUHdx8Giw',
        applemusic: 'https://music.apple.com/ee/album/this-is-happening/693391469',
    },
    Feb82023: {
        date: todaysDate,
        artist: 'Erykah Badu',
        artist2: 'Erykah Badu',
        album: 'Mama\'s Gun',
        album2: 'Mamas Gun',
        hint1: 'Genre: Neo Soul',
        hint2: 'Country: US',
        hint3: 'Release date: 2000',
        info: 'The cover takes on the colors of the reggae movement. The photo of the artist was taken by Robert Maxwell. The title is set in Amelia typeface, in yellow with a red flat shade.',
        spotify: 'https://open.spotify.com/album/3cADvHRdKniF9ELCn1zbGH?si=0SlimKDdRuCntxID4GT7rQ',
        applemusic: 'https://music.apple.com/ee/album/mamas-gun/1440755899',
    },
    Feb92023: {
        date: todaysDate,
        artist: 'A$AP Rocky',
        artist2: 'Asap Rocky',
        album: 'Long.Live.A$ap',
        album2: 'Long.Live.ASAP',
        hint1: 'Genre: Hip Hop, Cloud Rap',
        hint2: 'Country: US',
        hint3: 'Release date: 2013',
        info: 'Cover photo by Phil Knott. AD and design by Joe Perez, Creative Director Virgil Abloh. Fun story: Liam Gallagher once mistakenly referred to A$AP Rocky as "WhatsApp Ricky" during an interview.',
        spotify: 'https://open.spotify.com/album/6rzMufuu8sLkIizM4q9c7J?si=ihE7coDIQsmFukyOIzFMkQ',
        applemusic: 'https://music.apple.com/ee/album/long-live-a%24ap-deluxe-edition/1450690198',
    },
    Feb102023: {
        date: todaysDate,
        artist: 'HAIM',
        artist2: 'HAIM',
        album: 'Women in Music Pt. III',
        album2: 'Women in Music Pt 3',
        hint1: 'Genre: Soft Rock, plus a mix of everything else',
        hint2: 'Country: US',
        hint3: 'Release date: 2020',
        info: 'The album cover was shot at Canter’s Deli in Los Angeles by Paul Thomas Anderson, who also directed the music videos for all three singles and "The Steps", as well as for later directing the 2021 film Licorice Pizza which starred one of the band members — Alana Haim.',
        spotify: 'https://open.spotify.com/album/79thwyFL6Uo6rgTp3YWEAf?si=TrwZtVPdShSKeaBnW0IHKw',
        applemusic: 'https://music.apple.com/ee/album/women-in-music-pt-iii-expanded-edition/1553497808',
    },
    Feb122023: {
        date: todaysDate,
        artist: 'Santana',
        artist2: 'Carlos Santana',
        album: 'Supernatural',
        album2: 'Supernatural',
        hint1: 'Genre: Latin Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1999',
        info: 'Album cover adapted from a painting by Michael Rios.',
        spotify: 'https://open.spotify.com/album/10aiDpdFGyfCFEcqpx6XTq?si=1Ylwj5C2SCy2CsPIB6KyZA',
        applemusic: 'https://music.apple.com/ee/album/supernatural-remastered-bonus-track-version/354579273',
    },
    Feb132023: {
        date: todaysDate,
        artist: 'Stormzy',
        artist2: 'Stormzy',
        album: 'Heavy Is the Head',
        album2: 'Heavy Is the Head',
        hint1: 'Genre: Grime, Hip Hop',
        hint2: 'Country: UK',
        hint3: 'Release date: 2019',
        info: 'The cover shows Stormzy holding the stab proof vest featuring a black-and-white Union Jack that he wore during his set at the Glastonbury Festival 2019, designed by Banksy.',
        spotify: 'https://open.spotify.com/album/3y4AaloFccKNLQcZNS9L8c?si=4mPNHnyGToOtsFIGiSGjSg',
        applemusic: 'https://music.apple.com/ee/album/heavy-is-the-head/1450690198',
    },
    Feb142023: {
        date: todaysDate,
        artist: 'MGMT',
        artist2: 'MGMT',
        album: 'Congratulations',
        album2: 'Congratulations',
        hint1: 'Genre: Indie Rock, Psychedelic Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 2010',
        info: 'The cover art was done by Anthony Ausgang, known for his kitschy lowbrow art style.',
        spotify: 'https://open.spotify.com/album/3HA1Ru1gEAgaxTywkJmBOL?si=D961qyoEQm-oQFo-HchpWg',
        applemusic: 'https://music.apple.com/ee/album/congratulations/364168526',
    },
    Feb152023: {
        date: todaysDate,
        artist: 'Run the Jewels',
        artist2: 'RTJ',
        album: 'Run the Jewels 3',
        album2: 'RTJ3',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 2016',
        info: 'In an interview with Spin, Run the Jewels discussed the meaning of the album’s cover art: For us, the RTJ1 hands were about "taking what’s yours" – your world, your life, your attitude. The RTJ2 hands were wrapped in bandages, signifying injury and healing, which for us represented the growth in ideas and tone of that album. For RTJ3 the bandages are off, the chain is gone and the hands have been transformed into gold. For us this represents the idea that there is nothing to take that exists outside of yourself. You are the jewel.',
        spotify: 'https://open.spotify.com/album/2vY03PfKPFUUM1FA2lgmC2?si=Qmkkv97IQLa1pxI6cI03yQ',
        applemusic: 'https://music.apple.com/ee/album/run-the-jewels-3/1598920855',
    },
    Feb162023: {
        date: todaysDate,
        artist: 'R.E.M.',
        artist2: 'REM',
        album: 'Out of Time',
        album2: 'Out of Time',
        hint1: 'Genre: Alternative Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1991',
        info: 'In Spain, a contest was held to have a limited edition cover with the winner being an abstract oil painting.',
        spotify: 'https://open.spotify.com/album/6yEuIwTQpciH1qtj7mP5GK?si=7t502hJOTBKkRbCOZv085w',
        applemusic: 'https://music.apple.com/ee/album/out-of-time-2016-remaster/1440945025',
    },
    Feb172023: {
        date: todaysDate,
        artist: 'Joni Mitchell',
        artist2: 'Joni Mitchell',
        album: 'Blue',
        album2: 'Blue',
        hint1: 'Genre: Folk Rock',
        hint2: 'Country: Canada',
        hint3: 'Release date: 1971',
        info: 'Album cover shot by an American actor, writer, photographer, and automotive historian Tim Considine.',
        spotify: '',
        applemusic: 'https://music.apple.com/ee/album/blue/1492263092',
    },
    Feb182023: {
        date: todaysDate,
        artist: 'Bob Dylan',
        artist2: 'Bob Dylan',
        album: 'Highway 61 Revisited',
        album2: 'Highway 61',
        hint1: 'Genre: Folk Rock, Blues Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1965',
        info: 'The cover artwork was photographed by Daniel Kramer. Kramer captured Dylan sitting on the stoop of the apartment of his manager, Albert Grossman, located in Gramercy Park, New York, placing Dylan’s friend Bob Neuwirth behind Dylan "to give it extra color".',
        spotify: 'https://open.spotify.com/album/6YabPKtZAjxwyWbuO9p4ZD?si=qDM2vm5VSuqH0EUEaXWbgg',
        applemusic: 'https://music.apple.com/ee/album/highway-61-revisited/201281514',
    },
    Feb192023: {
        date: todaysDate,
        artist: 'Simon and Garfunkel',
        artist2: 'Simon & Garfunkel',
        album: 'Bridge over Troubled Water',
        album2: 'Bridge over Troubled Water',
        hint1: 'Genre: Folk Rock, Pop Rock',
        hint2: 'Country: US',
        hint3: 'Release date: 1970',
        info: 'The typeface used here is Helvetica and designed by Tony Lane. He became an early art director for Rolling Stone magazine and designed Michael Jackson’s “Bad”.',
        spotify: 'https://open.spotify.com/album/0JwHz5SSvpYWuuCNbtYZoV?si=kk-rju8kTcm2JhJi5KJU8w',
        applemusic: 'https://music.apple.com/ee/album/bridge-over-troubled-water/324127933',
    },
    Feb202023: {
        date: todaysDate,
        artist: 'Bruno Mars',
        artist2: 'Bruno Mars',
        album: '24K Magic',
        album2: '24k Magic',
        hint1: 'Genre: Pop, R&B, Funk',
        hint2: 'Country: US, Hawaii',
        hint3: 'Release date: 2016',
        info: 'Mars and Greg "Giden’s Dad" Burke created the artwork, which was shot by Chinese photographer Kai Z. Feng. According to Mars, the cover art was inspired by a "musky cologne" advertisement and the Cadillac Allanté convertible that felt like "bootleg luxury".',
        spotify: 'https://open.spotify.com/album/4PgleR09JVnm3zY1fW3XBA?si=2M7ohB1fRYCVZ1jzRFnkhA',
        applemusic: 'https://music.apple.com/ee/album/24k-magic/1161503945',
    },
    Feb212023: {
        date: todaysDate,
        artist: 'Olivia Rodrigo',
        artist2: 'Olivia Rodrigo',
        album: 'Sour',
        album2: 'Sour',
        hint1: 'Genre: Pop, Bedroom pop, Pop punk',
        hint2: 'Country: US',
        hint3: 'Release date: 2021',
        info: 'On the cover, the artist is positioned on a purble backdrop, where she sticks her tongue out, with her face covered in a variety of colorful stickers. The stickers on her tongue spell the album title. Photographed by Grant Spanier. In the alternative cover available for the Target-exclusive and vinyl editions of Sour, purple is again the dominant color, but stickers are not present.',
        spotify: 'https://open.spotify.com/album/6s84u2TUpR3wdUv4NgKA2j?si=7mEufRpkSq-OI7lXPfiZRA',
        applemusic: 'https://music.apple.com/ee/album/sour/1560735414',
    },
    Feb222023: {
        date: todaysDate,
        artist: 'Jay-Z',
        artist2: 'Jay-Z',
        album: 'The Blueprint 3',
        album2: 'The Blueprint III',
        hint1: 'Genre: Hip Hop',
        hint2: 'Country: US',
        hint3: 'Release date: 2009',
        info: 'The cover consists of a large number of all-white instruments and recording tools stacked in a corner, with three red lines across the image. Rather than simply using Photoshop, the album’s design team carefully stacked all the equipment in a corner then used a projector to create the bars. They then painted red onto the equipment where the projection of the bars was, and replaced the projector with a camera to achieve the correct perspective for the image. Blueprint 3 would be Jay-Z’s first album cover that did not feature his face on it. Creative Direction by Greg Gigendad Burke.',
        spotify: 'https://open.spotify.com/album/2CUT0104gySOIvqwtXeFsX?si=NvbqTC24TRmi2JrVjgkCrA',
        applemusic: 'https://music.apple.com/ee/album/the-blueprint-3/1440932327',
    },
}
let todaysData = Data[todaysDate];
export default todaysData;